// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: exported/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: EnemyTree001

	[behaviac.GeneratedTypeMetaInfo()]
	class End_bt_EnemyTree001_node0 : behaviac.End
	{
		public End_bt_EnemyTree001_node0()
		{
		}
		protected override EBTStatus GetStatus(Agent pAgent)
		{
			return behaviac.EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_EnemyTree001
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("EnemyTree001");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("BaseAgent");
#endif
			// children
			{
				End_bt_EnemyTree001_node0 node0 = new End_bt_EnemyTree001_node0();
				node0.SetClassNameString("End");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("BaseAgent");
#endif
				bt.AddChild(node0);
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
