// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

// -------------------
// Customized enums
// -------------------

public enum LogicStatus
{
	ELogic_IDLE = 0,
	ELogic_ATTACK = 1,
	ELogic_PATROL = 2,
	ELogic_TRACK = 3,
	ELogic_AIR = 4,
	ELogic_HURT = 5,
	ELogic_DEAD = 6,
	ELogic_JUMP = 7,
}

