// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: ../../Unity/Private/Beta-Navigation/AlphaWork/Assets/AlphaWork/Scripts/Game/Behaviour/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: CustomBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_CustomBT_node1 : behaviac.Assignment
	{
		public Assignment_bt_CustomBT_node1()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 8;
			behaviac.Agent pAgent_opl = behaviac.Utils.GetParentAgent(pAgent, "SecondAgentInstance");
			((SecondAgent)pAgent_opl).p2 = opr;
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_CustomBT_node2 : behaviac.Assignment
	{
		public Assignment_bt_CustomBT_node2()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 5;
			behaviac.Agent pAgent_opl = ((FirstAgent)pAgent).pInstance;
			((SecondAgent)pAgent_opl).p2 = opr;
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_CustomBT_node3 : behaviac.Condition
	{
		public Condition_bt_CustomBT_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.Agent pAgent_opl = behaviac.Utils.GetParentAgent(pAgent, "SecondAgentInstance");
			int opl = ((SecondAgent)pAgent_opl).p2;
			behaviac.Agent pAgent_opr = ((FirstAgent)pAgent).pInstance;
			int opr = ((SecondAgent)pAgent_opr).p2;
			bool op = opl > opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_CustomBT_node4 : behaviac.Action
	{
		public Action_bt_CustomBT_node4()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
			method_p0 = false;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello(method_p0);
			return EBTStatus.BT_SUCCESS;
		}
		bool method_p0;
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_CustomBT_node5 : behaviac.Action
	{
		public Action_bt_CustomBT_node5()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
			method_p0 = "hello subtree";
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).Say(ref method_p0);
			return EBTStatus.BT_SUCCESS;
		}
		string method_p0;
	}

	public static class bt_CustomBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("CustomBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence node0 = new Sequence();
				node0.SetClassNameString("Sequence");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				{
					Assignment_bt_CustomBT_node1 node1 = new Assignment_bt_CustomBT_node1();
					node1.SetClassNameString("Assignment");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Assignment_bt_CustomBT_node2 node2 = new Assignment_bt_CustomBT_node2();
					node2.SetClassNameString("Assignment");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node2);
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				{
					Condition_bt_CustomBT_node3 node3 = new Condition_bt_CustomBT_node3();
					node3.SetClassNameString("Condition");
					node3.SetId(3);
#if !BEHAVIAC_RELEASE
					node3.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node3);
					node0.SetHasEvents(node0.HasEvents() | node3.HasEvents());
				}
				{
					Action_bt_CustomBT_node4 node4 = new Action_bt_CustomBT_node4();
					node4.SetClassNameString("Action");
					node4.SetId(4);
#if !BEHAVIAC_RELEASE
					node4.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node4);
					node0.SetHasEvents(node0.HasEvents() | node4.HasEvents());
				}
				{
					Action_bt_CustomBT_node5 node5 = new Action_bt_CustomBT_node5();
					node5.SetClassNameString("Action");
					node5.SetId(5);
#if !BEHAVIAC_RELEASE
					node5.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node5);
					node0.SetHasEvents(node0.HasEvents() | node5.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: EnemyActorBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_EnemyActorBT_node1 : behaviac.Action
	{
		public Action_bt_EnemyActorBT_node1()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
			method_p0 = false;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello(method_p0);
			return EBTStatus.BT_SUCCESS;
		}
		bool method_p0;
	}

	public static class bt_EnemyActorBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("EnemyActorBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("SecondAgent");
#endif
			// children
			{
				Sequence node0 = new Sequence();
				node0.SetClassNameString("Sequence");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("SecondAgent");
#endif
				bt.AddChild(node0);
				{
					Action_bt_EnemyActorBT_node1 node1 = new Action_bt_EnemyActorBT_node1();
					node1.SetClassNameString("Action");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("SecondAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: SwtichStatusAction

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_SwtichStatusAction_node1 : behaviac.Condition
	{
		public Condition_bt_SwtichStatusAction_node1()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			LogicStatus opl = (LogicStatus)AgentMetaVisitor.GetProperty(pAgent, "m_LogicStatus");
			LogicStatus opr = LogicStatus.ELogic_PATROL;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_SwtichStatusAction_node3 : behaviac.Action
	{
		public Action_bt_SwtichStatusAction_node3()
		{
			this.m_resultOption = EBTStatus.BT_RUNNING;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((SecondAgent)pAgent).Patrol();
			return EBTStatus.BT_RUNNING;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_SwtichStatusAction_node4 : behaviac.Condition
	{
		public Condition_bt_SwtichStatusAction_node4()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			LogicStatus opl = (LogicStatus)AgentMetaVisitor.GetProperty(pAgent, "m_LogicStatus");
			LogicStatus opr = LogicStatus.ELogic_ATTACK;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_SwtichStatusAction_node5 : behaviac.Action
	{
		public Action_bt_SwtichStatusAction_node5()
		{
			this.m_resultOption = EBTStatus.BT_RUNNING;
			method_p0 = 0f;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((SecondAgent)pAgent).Attack(method_p0);
			return EBTStatus.BT_RUNNING;
		}
		float method_p0;
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_SwtichStatusAction_node6 : behaviac.Action
	{
		public Action_bt_SwtichStatusAction_node6()
		{
			this.m_resultOption = EBTStatus.BT_RUNNING;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((SecondAgent)pAgent).MakeIdle();
			return EBTStatus.BT_RUNNING;
		}
	}

	public static class bt_SwtichStatusAction
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("SwtichStatusAction");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("SecondAgent");
#endif
			// children
			{
				IfElse node0 = new IfElse();
				node0.SetClassNameString("IfElse");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("SecondAgent");
#endif
				bt.AddChild(node0);
				{
					Condition_bt_SwtichStatusAction_node1 node1 = new Condition_bt_SwtichStatusAction_node1();
					node1.SetClassNameString("Condition");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("SecondAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Action_bt_SwtichStatusAction_node3 node3 = new Action_bt_SwtichStatusAction_node3();
					node3.SetClassNameString("Action");
					node3.SetId(3);
#if !BEHAVIAC_RELEASE
					node3.SetAgentType("SecondAgent");
#endif
					node0.AddChild(node3);
					node0.SetHasEvents(node0.HasEvents() | node3.HasEvents());
				}
				{
					IfElse node2 = new IfElse();
					node2.SetClassNameString("IfElse");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("SecondAgent");
#endif
					node0.AddChild(node2);
					{
						Condition_bt_SwtichStatusAction_node4 node4 = new Condition_bt_SwtichStatusAction_node4();
						node4.SetClassNameString("Condition");
						node4.SetId(4);
#if !BEHAVIAC_RELEASE
						node4.SetAgentType("SecondAgent");
#endif
						node2.AddChild(node4);
						node2.SetHasEvents(node2.HasEvents() | node4.HasEvents());
					}
					{
						Action_bt_SwtichStatusAction_node5 node5 = new Action_bt_SwtichStatusAction_node5();
						node5.SetClassNameString("Action");
						node5.SetId(5);
#if !BEHAVIAC_RELEASE
						node5.SetAgentType("SecondAgent");
#endif
						node2.AddChild(node5);
						node2.SetHasEvents(node2.HasEvents() | node5.HasEvents());
					}
					{
						Action_bt_SwtichStatusAction_node6 node6 = new Action_bt_SwtichStatusAction_node6();
						node6.SetClassNameString("Action");
						node6.SetId(6);
#if !BEHAVIAC_RELEASE
						node6.SetAgentType("SecondAgent");
#endif
						node2.AddChild(node6);
						node2.SetHasEvents(node2.HasEvents() | node6.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
