//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AlphaWork_UIFunctionToolsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("UIFunctionTools");
		L.RegFunction("OpenUIFromId", OpenUIFromId);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenUIFromId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			AlphaWork.UIFunctionTools.OpenUIFromId(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

