//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AlphaWork_ConfigComponentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AlphaWork.ConfigComponent), typeof(UnityGameFramework.Runtime.GameFrameworkComponent));
		L.RegFunction("InitBuildInfo", InitBuildInfo);
		L.RegFunction("InitDefaultDictionary", InitDefaultDictionary);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("GameSetting", get_GameSetting, null);
		L.RegVar("MainScene", get_MainScene, set_MainScene);
		L.RegVar("DeviceModelConfig", get_DeviceModelConfig, null);
		L.RegVar("BuildInfo", get_BuildInfo, null);
		L.RegVar("UpdateResourceFormTemplate", get_UpdateResourceFormTemplate, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitBuildInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AlphaWork.ConfigComponent obj = (AlphaWork.ConfigComponent)ToLua.CheckObject<AlphaWork.ConfigComponent>(L, 1);
			obj.InitBuildInfo();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitDefaultDictionary(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AlphaWork.ConfigComponent obj = (AlphaWork.ConfigComponent)ToLua.CheckObject<AlphaWork.ConfigComponent>(L, 1);
			obj.InitDefaultDictionary();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameSetting(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AlphaWork.ConfigComponent obj = (AlphaWork.ConfigComponent)o;
			AlphaWork.GameSetting ret = obj.GameSetting;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GameSetting on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MainScene(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AlphaWork.ConfigComponent obj = (AlphaWork.ConfigComponent)o;
			int ret = obj.MainScene;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MainScene on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DeviceModelConfig(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AlphaWork.ConfigComponent obj = (AlphaWork.ConfigComponent)o;
			AlphaWork.DeviceModelConfig ret = obj.DeviceModelConfig;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DeviceModelConfig on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BuildInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AlphaWork.ConfigComponent obj = (AlphaWork.ConfigComponent)o;
			AlphaWork.BuildInfo ret = obj.BuildInfo;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BuildInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UpdateResourceFormTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AlphaWork.ConfigComponent obj = (AlphaWork.ConfigComponent)o;
			AlphaWork.UpdateResourceForm ret = obj.UpdateResourceFormTemplate;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index UpdateResourceFormTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MainScene(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AlphaWork.ConfigComponent obj = (AlphaWork.ConfigComponent)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.MainScene = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MainScene on a nil value");
		}
	}
}

