//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AlphaWork_GameEntryWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AlphaWork.GameEntry), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("RefreshLoginFlag", RefreshLoginFlag);
		L.RegFunction("RefreshBackToLoginFlag", RefreshBackToLoginFlag);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Base", get_Base, null);
		L.RegVar("DataNode", get_DataNode, null);
		L.RegVar("DataTable", get_DataTable, null);
		L.RegVar("Debugger", get_Debugger, null);
		L.RegVar("Download", get_Download, null);
		L.RegVar("Entity", get_Entity, null);
		L.RegVar("Event", get_Event, null);
		L.RegVar("Fsm", get_Fsm, null);
		L.RegVar("Localization", get_Localization, null);
		L.RegVar("Network", get_Network, null);
		L.RegVar("ObjectPool", get_ObjectPool, null);
		L.RegVar("Procedure", get_Procedure, null);
		L.RegVar("Resource", get_Resource, null);
		L.RegVar("Scene", get_Scene, null);
		L.RegVar("Setting", get_Setting, null);
		L.RegVar("Sound", get_Sound, null);
		L.RegVar("UI", get_UI, null);
		L.RegVar("LogIntoMain", get_LogIntoMain, null);
		L.RegVar("BackToLogin", get_BackToLogin, null);
		L.RegVar("WebRequest", get_WebRequest, null);
		L.RegVar("Config", get_Config, null);
		L.RegVar("Sensor", get_Sensor, null);
		L.RegVar("Behaviac", get_Behaviac, null);
		L.RegVar("NavGrid", get_NavGrid, null);
		L.RegVar("LuaScriptEngine", get_LuaScriptEngine, null);
		L.RegVar("DataBase", get_DataBase, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RefreshLoginFlag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
			AlphaWork.GameEntry.RefreshLoginFlag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RefreshBackToLoginFlag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
			AlphaWork.GameEntry.RefreshBackToLoginFlag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Base(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Base);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DataNode(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.DataNode);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DataTable(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.DataTable);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Debugger(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Debugger);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Download(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Download);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Entity(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Entity);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Event(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Event);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Fsm(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Fsm);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Localization(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Localization);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Network(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Network);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ObjectPool(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.ObjectPool);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Procedure(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Procedure);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Resource(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Resource);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Scene(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Scene);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Setting(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Setting);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Sound(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.Sound);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UI(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.UI);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LogIntoMain(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, AlphaWork.GameEntry.LogIntoMain);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackToLogin(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, AlphaWork.GameEntry.BackToLogin);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WebRequest(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, AlphaWork.GameEntry.WebRequest);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Config(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AlphaWork.GameEntry.Config);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Sensor(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AlphaWork.GameEntry.Sensor);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Behaviac(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AlphaWork.GameEntry.Behaviac);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NavGrid(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AlphaWork.GameEntry.NavGrid);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaScriptEngine(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AlphaWork.GameEntry.LuaScriptEngine);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DataBase(IntPtr L)
	{
		try
		{
			ToLua.Push(L, AlphaWork.GameEntry.DataBase);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

