//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AlphaWork_UGUIFormExtendWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AlphaWork.UGUIFormExtend), typeof(AlphaWork.UGuiForm));
		L.RegFunction("ProcedureImpl", ProcedureImpl);
		L.RegFunction("CreateUserImpl", CreateUserImpl);
		L.RegFunction("FillUserView", FillUserView);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ProcedureImpl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AlphaWork.UGUIFormExtend obj = (AlphaWork.UGUIFormExtend)ToLua.CheckObject<AlphaWork.UGUIFormExtend>(L, 1);
			obj.ProcedureImpl();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateUserImpl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AlphaWork.UGUIFormExtend obj = (AlphaWork.UGUIFormExtend)ToLua.CheckObject<AlphaWork.UGUIFormExtend>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.CreateUserImpl(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FillUserView(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AlphaWork.UGUIFormExtend obj = (AlphaWork.UGUIFormExtend)ToLua.CheckObject<AlphaWork.UGUIFormExtend>(L, 1);
			obj.FillUserView();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

