// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class BaseAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE BaseAgent
///<<< END WRITING YOUR CODE
{
	private float attackRadius = 10f;
	public void _set_attackRadius(float value)
	{
		attackRadius = value;
	}
	public float _get_attackRadius()
	{
		return attackRadius;
	}

	private bool bAwakeSense = false;
	public void _set_bAwakeSense(bool value)
	{
		bAwakeSense = value;
	}
	public bool _get_bAwakeSense()
	{
		return bAwakeSense;
	}

	private LogicStatus logicStatus = LogicStatus.ELogic_IDLE;
	public void _set_logicStatus(LogicStatus value)
	{
		logicStatus = value;
	}
	public LogicStatus _get_logicStatus()
	{
		return logicStatus;
	}

	private float senseRadius = 20f;
	public void _set_senseRadius(float value)
	{
		senseRadius = value;
	}
	public float _get_senseRadius()
	{
		return senseRadius;
	}

	public bool IsStatusValide()
	{
///<<< BEGIN WRITING YOUR CODE IsStatusValide
		return false;
///<<< END WRITING YOUR CODE
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART
//     protected AlphaWork.EntityObject m_parent;
//     public AlphaWork.EntityObject Parent
//     {
//         get { return m_parent; }
//         set { m_parent = value; }
//     }
    protected int m_ParentId;
    public int ParentId
    {
        get { return m_ParentId; }
        set { m_ParentId = value; }
    }    
    ///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

