// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class BaseAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE BaseAgent
///<<< END WRITING YOUR CODE
{
	private LogicStatus m_LogicStatus = LogicStatus.ELogic_IDLE;
	public void _set_m_LogicStatus(LogicStatus value)
	{
		m_LogicStatus = value;
	}
	public LogicStatus _get_m_LogicStatus()
	{
		return m_LogicStatus;
	}

	private List<int> m_Sensors = new List<int>(0) {};
	public void _set_m_Sensors(List<int> value)
	{
		m_Sensors = value;
	}
	public List<int> _get_m_Sensors()
	{
		return m_Sensors;
	}

	public bool IsStatusValide()
	{
///<<< BEGIN WRITING YOUR CODE IsStatusValide
		return false;
///<<< END WRITING YOUR CODE
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART
//     protected AlphaWork.EntityObject m_parent;
//     public AlphaWork.EntityObject Parent
//     {
//         get { return m_parent; }
//         set { m_parent = value; }
//     }
    protected int m_ParentId;
    public int ParentId
    {
        get { return m_ParentId; }
        set { m_ParentId = value; }
    }
    ///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

