// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class BaseAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE BaseAgent
///<<< END WRITING YOUR CODE
{
	private bool bAwakeSense = false;
	public void _set_bAwakeSense(bool value)
	{
		bAwakeSense = value;
	}
	public bool _get_bAwakeSense()
	{
		return bAwakeSense;
	}

	private LogicStatus logicStatus = LogicStatus.ELogic_IDLE;
	public void _set_logicStatus(LogicStatus value)
	{
		logicStatus = value;
	}
	public LogicStatus _get_logicStatus()
	{
		return logicStatus;
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART
    protected int m_ParentId;
    public int ParentId
    {
        get { return m_ParentId; }
        set { m_ParentId = value; }
    }
    protected float SqAdd(float x)
    {
        return (float)Math.Sqrt(2 * x * x);
    }
    protected bool InRange(float val, float min, float max)
    {
        return (val <= max && val > min);
    }
    ///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

