// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

// -------------------
// Customized enums
// -------------------

public enum LogicStatus
{
	ELogic_IDLE = 0,
	ELogic_PATROL = 1,
	ELogic_ATTACK = 2,
}

