// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class FirstAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE FirstAgent
///<<< END WRITING YOUR CODE
{
	private LogicStatus m_LogicStatus = LogicStatus.ELogic_IDLE;
	public void _set_m_LogicStatus(LogicStatus value)
	{
		m_LogicStatus = value;
	}
	public LogicStatus _get_m_LogicStatus()
	{
		return m_LogicStatus;
	}

	private int p1 = 0;
	public void _set_p1(int value)
	{
		p1 = value;
	}
	public int _get_p1()
	{
		return p1;
	}

	public SecondAgent pInstance = null;

	public void FlushEnemies()
	{
///<<< BEGIN WRITING YOUR CODE FlushEnemies
///<<< END WRITING YOUR CODE
	}

	public LogicStatus GetLogicStatus()
	{
///<<< BEGIN WRITING YOUR CODE GetLogicStatus
		return m_LogicStatus;
///<<< END WRITING YOUR CODE
	}

	public bool IsHit(string checkEntity)
	{
///<<< BEGIN WRITING YOUR CODE IsHit
		return false;
///<<< END WRITING YOUR CODE
	}

	public void Say(ref string param0)
	{
///<<< BEGIN WRITING YOUR CODE Say
///<<< END WRITING YOUR CODE
	}

	public void SayHello(bool bEnd)
	{
///<<< BEGIN WRITING YOUR CODE SayHello
///<<< END WRITING YOUR CODE
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART
    protected AlphaWork.EntityObject m_parent;
    public AlphaWork.EntityObject Parent
    {
        get { return m_parent; }
        set { m_parent = value;}
    }
///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

