--[[
    **************************
        面板功能注册，用于统一打开面板 调用重写的基类方法DoCreate 17/07/11
        flyfish
    **************************
]]
local GUIHandlers = {
    --[[ [EFuncType.Loading] = require("Game.Common.ui.UILoading").Instance(),
    [EFuncType.Start] = require("Game.Start.ui.UIStart").Instance(),
    [EFuncType.Login] = require("Game.Login.ui.UILogin").Instance(),
    [EFuncType.GameHall] = require("Game.GameHall.ui.UIGameHall").Instance(),
    --[EFuncType.PetBag] = require("Game.PetBag.ui.UIPetBag").Instance(),
    [EFuncType.BattleMatch] = require("Game.BattleMatch.ui.UIBattleMatch").Instance(),
    [EFuncType.Tips] = require("Game.Tips.ui.UITips").Instance(),
    [EFuncType.SelectHero] = require("Game.SelectHero.ui.UISelectHero").Instance(),
    [EFuncType.HeroArray] = require("Game.HeroArray.ui.UIHeroArray").Instance(),
    [EFuncType.Settlement] = require("Game.Settlement.ui.UISettlement").Instance(),
    [EFuncType.HeroArchive] = require("Game.HeroArchive.ui.UIHeroArchive").Instance(),
    [EFuncType.HeroInfo] = require("Game.HeroInfo.ui.UIHeroInfo").Instance(),
    [EFuncType.Combat] = require("Game.Combat.ui.UICombat").Instance(),
    [EFuncType.SummonPet] = require("Game.BeastPet.ui.UISummonPet").Instance(),
    [EFuncType.PetDetail] = require("Game.BeastPet.ui.UIPetDetail").Instance(),
    [EFuncType.BuyTips] = require("Game.BuyTips.ui.UIBuyTips").Instance(),
    [EFuncType.BuyDisplay] = require("Game.BuyDisplay.ui.UIBuyDisplay").Instance(),
    [EFuncType.SkillInfoPanel] = require("Game.SkillInfoPanel.ui.UISkillInfoPanel").Instance(),
    -- [EFuncType.TempHead] = require("Game.Combat.ui.UITempHeadMgr").Instance(),
    [EFuncType.PetEdit] = require("Game.Pet.ui.UIPet_Fight").Instance(),
    [EFuncType.UnitHead] = require("Game.Combat.ui.UIUnitHeadMgr").Instance(),
    [EFuncType.Reward] = require("Game.Reward.ui.UIReward").Instance(),
    [EFuncType.GetCoin] = require("Game.GetCoin.ui.UIGetCoin").Instance(),
    [EFuncType.BattleHeroInfo] = require("Game.BattleHeroInfo.ui.UIBattleInfo").UIBattleInfo.Instance(),
    [EFuncType.PetArchive] = require("Game.PetArchive.ui.UIPetArchive").Instance(),
    [EFuncType.CenterNotice] = require("Game.CenterNotice.ui.UICenterNoticeMgr").Instance(),
    [EFuncType.Waiting] = require("Game.Common.ui.UIWaiting").Instance(),
	[EFuncType.Pet] = require("Game.Pet.ui.UIPet_Main").Instance(),
    [EFuncType.PetTrain_SubPageMain] = require("Game.Pet.UI.UIPetTrain_SubPage_Main").Instance(),
    [EFuncType.Pet_LearnskillMain] = require("Game.Pet.UI.UIPet_LearnSkill").Instance(),
    [EFuncType.FULLSCREEN_OPR] = require("Game.Common.ui.UIFullScreenOpr").Instance(),
    [EFuncType.NORMAL_REWARD] = require("Game.Common.ui.UINormaleReward").UINormaleReward.Instance(),
    [EFuncType.Chat] = require("Game.Chat.ui.UIChat").Instance(),
    [EFuncType.ChatMain] = require("Game.Chat.ui.UIChatMain").Instance(),
    [EFuncType.FlashDialog] = require("Game.Common.ui.UIFlashDialog").Instance(),
    [EFuncType.PetInfo] = require("Game.PetInfo.UIPetInfo").Instance(),
    [EFuncType.PlayerHeadInfo] = require("Game.PlayerHeadInfo.UIPlayerHeadInfo").Instance(),
	[EFuncType.Bag] = require("Game.Bag.ui.UIBag_Main").Instance(),
    [EFuncType.MagicWeapon] = require("Game.MagicWeapon.ui.UIMagicWeapon").Instance(),
    [EFuncType.MagicWeaponView] = require("Game.MagicWeapon.ui.UIMagicWeaponView").Instance(),
    [EFuncType.Money] = require("Game.Money.ui.UIMoney").Instance(),
    [EFuncType.SelectTrump] = require("Game.MagicWeapon.ui.UISelectTrump").Instance(),
    [EFuncType.TrumpEffect] = require("Game.MagicWeapon.ui.UIMagicWeaponEffect").Instance(),
    [EFuncType.SelectionMode] = require("Game.BattleMatch.ui.UISelectionMode").Instance(),
    [EFuncType.UIPet_Summon] = require("Game.Pet.ui.UIPet_Summon").Instance(),
    [EFuncType.UITeam_Match] = require("Game.BattleMatch.ui.UITeamMatch").Instance(),
    [EFuncType.UITeamInvite] = require("Game.BattleMatch.ui.UITeamInvite").Instance(),
    [EFuncType.UIMatchHang] = require("Game.BattleMatch.ui.UIMatchHang").Instance(),
    [EFuncType.UITeaminvited] = require("Game.BattleMatch.ui.UITeaminvited").Instance(),
    [EFuncType.Posy_Court] = require("Game.Posy.ui.UIPosy_Court").Instance(),
    [EFuncType.Posy_Lottery] = require("Game.Posy.ui.UIPosy_Lottery").Instance(),
    [EFuncType.Posy_Main] = require("Game.Posy.ui.UIPosy_Main").Instance(),
    [EFuncType.UIRankingMatch] = require("Game.BattleMatch.ui.UIRankingMatch").Instance(),
    [EFuncType.UIRank] = require("Game.Rank.ui.UIRank").Instance(),
    [EFuncType.UISegmentDisplay] = require("Game.BattleMatch.ui.UISegmentDisplay").Instance(),
    [EFuncType.UISeasonReward] = require("Game.BattleMatch.ui.UISeasonReward").Instance(),
    [EFuncType.Foreword] = require("Game.Common.ui.UIForeword").Instance(),
    [EFuncType.Hero_Illustration] = require("Game.Hero.ui.UIHero_Illustration").Instance(),
    [EFuncType.HeroInfo_Main] = require("Game.Hero.ui.UIHeroInfo_Main").Instance(),
    [EFuncType.Hero_Display] = require("Game.Hero.ui.UIHero_Display").Instance(),
    [EFuncType.UISelectHeroNew] = require("Game.SelectHero.ui.UISelectHeroNew").Instance(),
    [EFuncType.Task_Main] = require("Game.Grow.ui.UITask_Main").Instance(),
    [EFuncType.Task_Grow] = require("Game.Grow.ui.UITask_Grow").Instance(),
    [EFuncType.UISingleHang] = require("Game.BattleMatch.ui.UISingleHang").Instance(),
    [EFuncType.UIPet_Illustration] = require("Game.Pet.ui.UIPet_Illustration").Instance(),
    [EFuncType.UIPetDetailNew] = require("Game.Pet.ui.UIPet_detail_New").Instance(), ]]
}
return GUIHandlers
